GHA: regression update

diff --git a/.github/workflows/modules.yml b/.github/workflows/modules.yml
--- a/.github/workflows/modules.yml
+++ b/.github/workflows/modules.yml
@@ -199,13 +199,6 @@ jobs:
         name: inviwo-python-api
         path: build/docs/python-api/*
     
-    - name: "Setup tmate session (on failure and debug_enabled)"
-      if: "${{ failure() && contains( github.event.pull_request.labels.*.name, 'CI: Debug') }}"
-      uses: mxschmitt/action-tmate@v3
-      timeout-minutes: 30
-      with:
-        limit-access-to-actor: true
-    
     - name: "Upload Vcpkg build Logs"
       if: "${{ failure() }}"
       uses: actions/upload-artifact@v4
@@ -213,9 +206,18 @@ jobs:
         name: vcpkg-logs-${{ matrix.system }}-${{ matrix.linkage }}-${{ matrix.configuration }}
         path: vcpkg/buildtrees/**/*.log
 
+    - name: "Setup tmate session (on failure and debug_enabled)"
+      if: "${{ failure() && contains( github.event.pull_request.labels.*.name, 'CI: Debug') }}"
+      uses: mxschmitt/action-tmate@v3
+      timeout-minutes: 30
+      with:
+        limit-access-to-actor: true
+
   regression:
     name: "Regression"
     runs-on: [regression, macOS]
+    permissions:
+      pull-requests: write
     timeout-minutes: 320
     steps:
 
@@ -223,7 +225,6 @@ jobs:
       uses: actions/checkout@v4
       with:
         path: modules
-        submodules: false
 
     - name: "Clone Inviwo"
       uses: actions/checkout@v4
@@ -231,7 +232,20 @@ jobs:
         repository: inviwo/inviwo
         ref: master
         path: inviwo
-        submodules: false
+
+    - name: "Get Vcpkg SHA"
+      shell: bash
+      run: |
+        SHA=`jq -r '.["vcpkg-configuration"].["default-registry"].baseline' inviwo/vcpkg.json`
+        echo "VCPKG_SHA=${SHA}" >> $GITHUB_ENV
+
+    - name: "VCPKG Update"
+      shell: bash
+      run: |
+        cd $VCPKG_INSTALLATION_ROOT
+        git fetch
+        git checkout $VCPKG_SHA
+        ./bootstrap-vcpkg.sh
 
     - name: Copy Preset
       shell: bash
@@ -263,15 +277,17 @@ jobs:
         echo "::remove-matcher owner=linker::"
 
     - name: "Unit Tests"
+      id: unit_tests
+      continue-on-error: true
       shell: bash
       working-directory: "build"
-      continue-on-error: true
       run: ctest -C RelWithDebInfo --output-on-failure
 
     - name: "Integration Tests"
-      shell: bash
-      working-directory: "build/bin"
+      id: integration
       continue-on-error: true
+      shell: bash
+      working-directory: "build/bin/RelWithDebInfo"
       run: ./inviwo-integrationtests
 
     - name: "Clone Regression"
@@ -283,8 +299,9 @@ jobs:
         path: regression
 
     - name: "Regression Tests"
-      shell: bash
+      id: regression
       continue-on-error: true
+      shell: bash
       run: |
         mkdir -p regression/modules/macos/${{ github.ref }}
         python3 inviwo/tools/regression.py \
@@ -306,6 +323,61 @@ jobs:
 
         echo "### :chart_with_upwards_trend: Regression report at https://inviwo.org/regression/modules/macos/${{ github.ref }}/report.html " >> $GITHUB_STEP_SUMMARY
 
+    - name: Summary
+      if: "${{ github.ref != 'refs/heads/master' }}"
+      shell: bash
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GH_REPO: ${{ github.repository }}
+        NUMBER: ${{ github.event.pull_request.number }}
+        UNIT_TESTS: "${{ steps.unit_tests.outcome }}"
+        INTEGRATION: ${{ steps.integration.outcome }}
+        REGRESSION: ${{ steps.regression.outcome }}
+      run: |
+        if [[ ${UNIT_TESTS} == "failure" ]]
+        then
+          gh pr edit "$NUMBER" --add-label "J: Unit Test Failure"
+          echo "### :bug: Unit Test Failure:bangbang:  \n" >> $GITHUB_STEP_SUMMARY
+        fi
+        if [[ ${UNIT_TESTS} == "success" ]]
+        then
+          gh pr edit "$NUMBER" --remove-label "J: Unit Test Failure" || true
+        fi
+
+        if [[ ${INTEGRATION} == "failure" ]]
+        then
+          gh pr edit "$NUMBER" --add-label "J: Integration Test Failure"
+          echo "### :bug: Integration Test Failure:bangbang:  \n" >> $GITHUB_STEP_SUMMARY
+        fi
+        if [[ ${INTEGRATION} == "success" ]]
+        then
+          gh pr edit "$NUMBER" --remove-label "J: Integration Test Failure" || true
+        fi
+
+        if [[ ${REGRESSION} == "failure" ]]
+        then
+          gh pr edit "$NUMBER" --add-label "J: Regression Test Failure"
+          echo "### :beetle: Regression Test Failure:bangbang:  \n" >> $GITHUB_STEP_SUMMARY
+        fi
+        if [[ ${REGRESSION} == "success" ]]
+        then
+          gh pr edit "$NUMBER" --remove-label "J: Regression Test Failure" || true
+        fi
+
+    - name: Exit
+      shell: bash
+      env:
+        UNIT_TESTS: ${{ steps.unit_tests.outcome }}
+        INTEGRATION: ${{ steps.integration.outcome }}
+        REGRESSION: ${{ steps.regression.outcome }}
+      run: |
+        if [[ ${UNIT_TESTS} == "success" ]] && [[ ${INTEGRATION} == "success" ]] && [[ ${REGRESSION} == "success" ]]
+        then
+          exit 0
+        else
+          exit 1
+        fi
+
   clang-tidy:
     name: "Clang-tidy"
     if: github.ref != 'refs/heads/master'
@@ -321,7 +393,6 @@ jobs:
       uses: actions/checkout@v4
       with:
         path: modules
-        submodules: false
 
     - name: "Clone Inviwo"
       uses: actions/checkout@v4
@@ -329,7 +400,6 @@ jobs:
         repository: inviwo/inviwo
         ref: master
         path: inviwo
-        submodules: false
         
     - name: "Install dependencies"
       uses: ./inviwo/.github/actions/install-dependencies
@@ -380,6 +450,13 @@ jobs:
         thread-comments: update
         file-annotations: false
         verbosity: debug
+
+    - name: "Upload Vcpkg build Logs"
+      if: "${{ failure() }}"
+      uses: actions/upload-artifact@v4
+      with:
+        name: vcpkg-logs-clang-tidy
+        path: vcpkg/buildtrees/**/*.log
         
     - name: "Setup tmate session (on failure and debug_enabled)"
       if: "${{ failure() && contains( github.event.pull_request.labels.*.name, 'CI: Debug') }}"
